name: Deploy

on:
  schedule:
    - cron: '0 0 */7 * *'
  push:
    branches: [ main ]


jobs:
    convert-and-upload:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Download Excel file
          run: |
            curl -o 2024_Spring_Summer.xlsx "https://docs.qq.com/sheet/DVEpjc3FuSUltVWNM?u=1c4a375951a947ad9ae08e18ae147e9c&tab=gccqz2"
    
        - name: Convert Excel to HTML
          run: python excel2html.py
    
        - name: Upload HTML file to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "seminar.html"
            target: "/home/wwwroot/default"