name: Deploy

on:
  schedule:
    - cron: '0 0 */7 * *'
  push:
    branches: [ main ]


jobs:
    convert-and-upload:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Convert Excel to HTML
          run: python excel2html.py
    
        - name: Upload HTML file to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: 22
            source: "seminar.html"
            target: "/home/wwwroot/default"